name: Tests
on:
  push:
    branches:
      - bench64
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test
    env:
      DOCKER_BUILDKIT: 1
      OUTPUT: ${{ github.workspace }}/result.csv
    steps:
    - uses: actions/checkout@v4
    - name: test
      run: |
        cd examples/benchmarks/
        for I in {1..3} ; do ./run.sh "$OUTPUT" ; done
    - name: result
      run: |
        cd examples/benchmarks/
        for TARGET in $(ls -1 ./targets/) ; do
          echo -n "${TARGET}: "
          echo "$(cat $OUTPUT | grep $TARGET | cut -f 5 -d,) / $(cat $OUTPUT | grep $TARGET | wc -l)" | bc
        done
